apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: JWT_SECRET
            - name: MYSQL_DATABASE
            - name: MYSQL_HOST
            - name: MYSQL_PASSWORD
            - name: MYSQL_PORT
            - name: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
            - name: PORT
            - name: SALT_ROUNDS
          image: api
          name: node-api
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/app/logs
              name: api-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: api-cm0
          name: api-cm0
