services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_api
    restart: always
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
