services:
  test_db:
    image: mysql:8.0
    container_name: mysql_test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_TEST_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_USER: ${MYSQL_TEST_USER}
      MYSQL_PASSWORD: ${MYSQL_TEST_PASSWORD}
      MYSQL_PORT: ${MYSQL_TEST_PORT}
      MYSQL_HOST: ${MYSQL_TEST_HOST}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  api_test:
    environment:
      MYSQL_TEST_ROOT_PASSWORD: ${MYSQL_TEST_ROOT_PASSWORD}
      MYSQL_TEST_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_TEST_USER: ${MYSQL_TEST_USER}
      MYSQL_TEST_PASSWORD: ${MYSQL_TEST_PASSWORD}
      MYSQL_TEST_PORT: ${MYSQL_TEST_PORT}
      MYSQL_TEST_HOST: ${MYSQL_TEST_HOST}
      PORT: ${PORT}
      SALT_ROUNDS: ${SALT_ROUNDS}
      JWT_SECRET: ${JWT_SECRET}
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test_node_api
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - test_db

