const comments = [
  {
    postId: 1,
    id: 1,
    name: "Alice Smith",
    email: "alice.smith@example.com",
    body: "Great article! I learned a lot about JavaScript closures. Thanks for sharing!",
  },
  {
    postId: 2,
    id: 2,
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    body: "Very informative post on SEO. I'll definitely use these tips to improve my website's ranking.",
  },
  {
    postId: 3,
    id: 3,
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    body: "This introduction to machine learning was exactly what I needed. Clear and concise.",
  },
  {
    postId: 4,
    id: 4,
    name: "Dana White",
    email: "dana.white@example.com",
    body: "Cybersecurity is so important these days. Thanks for highlighting the key points.",
  },
  {
    postId: 5,
    id: 5,
    name: "Evan Davis",
    email: "evan.davis@example.com",
    body: "Excellent time management strategies. I can't wait to implement them in my daily routine.",
  },
  {
    postId: 6,
    id: 6,
    name: "Fiona Green",
    email: "fiona.green@example.com",
    body: "Cryptocurrency and blockchain can be confusing, but this post made it much clearer.",
  },
  {
    postId: 7,
    id: 7,
    name: "George Harris",
    email: "george.harris@example.com",
    body: "Exercise really does help with mental health. Great read!",
  },
  {
    postId: 8,
    id: 8,
    name: "Hannah Clark",
    email: "hannah.clark@example.com",
    body: "Cloud computing has so many benefits. Thanks for breaking it down.",
  },
  {
    postId: 9,
    id: 9,
    name: "Ivy Lewis",
    email: "ivy.lewis@example.com",
    body: "AI in healthcare is fascinating. Looking forward to more advancements in this field.",
  },
  {
    postId: 10,
    id: 10,
    name: "Jack Robinson",
    email: "jack.robinson@example.com",
    body: "Building a remote team can be challenging. These tips will be very useful.",
  },
  {
    postId: 1,
    id: 11,
    name: "Kelly Martinez",
    email: "kelly.martinez@example.com",
    body: "Mindfulness has changed my life. Thanks for sharing these techniques.",
  },
  {
    postId: 2,
    id: 12,
    name: "Liam Moore",
    email: "liam.moore@example.com",
    body: "Python is so powerful for data science. Great introductory post.",
  },
  {
    postId: 3,
    id: 13,
    name: "Mia Thompson",
    email: "mia.thompson@example.com",
    body: "Renewable energy is the future. Thanks for this insightful article.",
  },
  {
    postId: 4,
    id: 14,
    name: "Noah Wilson",
    email: "noah.wilson@example.com",
    body: "Social media has its pros and cons. This was a balanced view.",
  },
  {
    postId: 5,
    id: 15,
    name: "Olivia Anderson",
    email: "olivia.anderson@example.com",
    body: "Personal finance management is crucial. These strategies are very helpful.",
  },
  {
    postId: 6,
    id: 16,
    name: "Paul Walker",
    email: "paul.walker@example.com",
    body: "Understanding habit formation can really help build better routines.",
  },
  {
    postId: 7,
    id: 17,
    name: "Quinn Allen",
    email: "quinn.allen@example.com",
    body: "IoT has so many applications. This was a great overview.",
  },
  {
    postId: 8,
    id: 18,
    name: "Ryan Scott",
    email: "ryan.scott@example.com",
    body: "Learning a second language has so many benefits. Thanks for sharing.",
  },
  {
    postId: 9,
    id: 19,
    name: "Sophie Young",
    email: "sophie.young@example.com",
    body: "E-commerce trends are changing rapidly. Great insights.",
  },
  {
    postId: 10,
    id: 20,
    name: "Tommy King",
    email: "tommy.king@example.com",
    body: "Content marketing is key to engagement. Thanks for the strategy tips.",
  },
  {
    postId: 1,
    id: 21,
    name: "Uma Carter",
    email: "uma.carter@example.com",
    body: "Emotional intelligence is so important in leadership. Great read.",
  },
  {
    postId: 2,
    id: 22,
    name: "Victor Turner",
    email: "victor.turner@example.com",
    body: "Investing in the stock market can be intimidating. This guide was very helpful.",
  },
  {
    postId: 3,
    id: 23,
    name: "Wendy Perez",
    email: "wendy.perez@example.com",
    body: "Public speaking skills can really boost your career. Thanks for the tips.",
  },
  {
    postId: 4,
    id: 24,
    name: "Xander Ramirez",
    email: "xander.ramirez@example.com",
    body: "Big data is transforming business. Great explanation of its benefits.",
  },
  {
    postId: 5,
    id: 25,
    name: "Yara Morgan",
    email: "yara.morgan@example.com",
    body: "Gratitude can change your perspective. Thanks for the practical tips.",
  },
  {
    postId: 6,
    id: 26,
    name: "Zane Cook",
    email: "zane.cook@example.com",
    body: "The evolution of AI is fascinating. Thanks for this detailed overview.",
  },
  {
    postId: 7,
    id: 27,
    name: "Aaron Bell",
    email: "aaron.bell@example.com",
    body: "Developing a growth mindset is crucial for success. Great tips.",
  },
  {
    postId: 8,
    id: 28,
    name: "Bella Foster",
    email: "bella.foster@example.com",
    body: "Work-life balance is so important. These strategies are very helpful.",
  },
  {
    postId: 9,
    id: 29,
    name: "Caleb Brooks",
    email: "caleb.brooks@example.com",
    body: "Sustainable living is essential. Thanks for the practical advice.",
  },
  {
    postId: 10,
    id: 30,
    name: "Diana Murphy",
    email: "diana.murphy@example.com",
    body: "Mind mapping is a great tool. Thanks for the detailed guide.",
  },
  {
    postId: 1,
    id: 31,
    name: "Eli Nguyen",
    email: "eli.nguyen@example.com",
    body: "Quantum computing has so much potential. Thanks for the insights.",
  },
  {
    postId: 2,
    id: 32,
    name: "Faith Hayes",
    email: "faith.hayes@example.com",
    body: "Diversity and inclusion are crucial in the workplace. Great article.",
  },
  {
    postId: 3,
    id: 33,
    name: "Grace Collins",
    email: "grace.collins@example.com",
    body: "Reading every day has changed my life. Thanks for the encouragement.",
  },
  {
    postId: 4,
    id: 34,
    name: "Henry Simmons",
    email: "henry.simmons@example.com",
    body: "Creating a budget is the first step to financial stability. Great tips.",
  },
  {
    postId: 5,
    id: 35,
    name: "Isabella Ross",
    email: "isabella.ross@example.com",
    body: "Nutrition is key to good health. Thanks for the comprehensive guide.",
  },
  {
    postId: 6,
    id: 36,
    name: "James Ward",
    email: "james.ward@example.com",
    body: "Meditation has so many benefits. Thanks for the beginner tips.",
  },
  {
    postId: 7,
    id: 37,
    name: "Kylie Adams",
    email: "kylie.adams@example.com",
    body: "Technology is transforming education. Great insights into its impact.",
  },
  {
    postId: 8,
    id: 38,
    name: "Logan Turner",
    email: "logan.turner@example.com",
    body: "Building resilience is so important. Thanks for the practical advice.",
  },
  {
    postId: 9,
    id: 39,
    name: "Mason Nelson",
    email: "mason.nelson@example.com",
    body: "Volunteering has so many benefits. Thanks for the motivation to get involved.",
  },
  {
    postId: 10,
    id: 40,
    name: "Nina Scott",
    email: "nina.scott@example.com",
    body: "Setting boundaries is essential for healthy relationships. Great advice.",
  },
  {
    postId: 1,
    id: 41,
    name: "Owen Evans",
    email: "owen.evans@example.com",
    body: "Digital marketing is crucial. Thanks for the comprehensive guide.",
  },
  {
    postId: 2,
    id: 42,
    name: "Paige Baker",
    email: "paige.baker@example.com",
    body: "Sleep is so important for health. Thanks for the tips on improving sleep quality.",
  },
  {
    postId: 3,
    id: 43,
    name: "Quincy Phillips",
    email: "quincy.phillips@example.com",
    body: "Outdoor activities are great for health. Thanks for the suggestions.",
  },
  {
    postId: 4,
    id: 44,
    name: "Riley Campbell",
    email: "riley.campbell@example.com",
    body: "Critical thinking is essential. Thanks for the tips on how to develop it.",
  },
  {
    postId: 5,
    id: 45,
    name: "Samantha Mitchell",
    email: "samantha.mitchell@example.com",
    body: "Sustainable fashion is so important. Thanks for the practical tips.",
  },
  {
    postId: 6,
    id: 46,
    name: "Tyler Perez",
    email: "tyler.perez@example.com",
    body: "The science of happiness is fascinating. Thanks for sharing these strategies.",
  },
  {
    postId: 7,
    id: 47,
    name: "Uma Cooper",
    email: "uma.cooper@example.com",
    body: "A plant-based diet has so many benefits. Thanks for the guide on getting started.",
  },
  {
    postId: 8,
    id: 48,
    name: "Violet Reed",
    email: "violet.reed@example.com",
    body: "Communication skills are so important. Thanks for the practical tips.",
  },
  {
    postId: 9,
    id: 49,
    name: "Will Harris",
    email: "will.harris@example.com",
    body: "Financial literacy is crucial. Thanks for the tips on how to improve it.",
  },
  {
    postId: 10,
    id: 50,
    name: "Xenia Gray",
    email: "xenia.gray@example.com",
    body: "Minimalism has so many benefits. Thanks for the guide on embracing a simpler lifestyle.",
  },
];

module.exports = comments;
