@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQHVzZXIuZWUiLCJyb2xlIjoidXNlciIsImlhdCI6MTcxNjk2MTMxOCwiZXhwIjoxNzE2OTY0OTE4fQ.tNnqfhJ9syxhSwsp_IQ0Dn7BDX5QO6mOgG_-YXwQjVU

### Get all posts
GET {{baseUrl}}/posts

### Get a post by id
GET {{baseUrl}}/posts/52

### Create a post
POST {{baseUrl}}/posts
Authorization: Bearer {{token}}
content-type: application/json

{
    "title": "Post 1",
    "body": "Content 1"
}

